name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      SECRET: ${{ secrets.SECRET }}
      TEST_MONGO_URI: ${{ secrets.TEST_MONGO_URI }}
    steps:
      - name: check
        run: echo "hello"
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: npm install backend
        run: npm install
      - name: npm install frontend
        run: cd bloglist-frontend && npm install
      - name: eslint backend
        run: npm run eslint
      - name: eslint frontend
        run: cd bloglist-frontend && npm run eslint
      - name: unit testing backend
        run: npm run test
      - name: build
        run: npm run build
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run cypress
          start: npm start && cd bloglist-frontend
          wait-on: http://localhost:3001
