name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      SECRET: ${{ secrets.SECRET }}
      TEST_MONGO_URI:
    steps:
      - name: check
        run: echo "hello"
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      # - name: Make envfile
      #   uses: SpicyPizza/create-envfile@v1
      #   with:
      #     envkey_MONGO_URI: ${{ secrets.MONGO_URI }}
      #     envkey_SECRET: ${{ secrets.SECRET }}
      #     #directory: <directory_name>
      #     file_name: .env

      # - name: check .env
      #   run: ls -al && cat  .env
      - name: npm install backend
        run: npm install
      - name: npm install frontend
        run: cd bloglist-frontend && npm install
      - name: eslint backend
        run: npm run eslint
      - name: eslint frontend
        run: cd bloglist-frontend && npm run eslint
      - name: unit testing backend
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          SECRET: ${{ secrets.SECRET }}
        run: npm run test
      - name: build
        run: npm run build
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: cd bloglist-frontend && npm run cypress
          start: npm start
          wait-on: http://localhost:3001
